name: nl_cl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.1
  - numpy
  - pillow
  - scikit-learn
  - matplotlib
  - pyyaml
  - tqdm
  - tensorboard
  - requests
  - typing_extensions
  - pip
  - pip:
      - opencv-python
      - kagglehub
